name: Release

on:
  push:
    branches: [ main-cmaster11 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: npm
      - run: |
          set -euo pipefail
          npm ci
          npm run jest
          npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: release-dist
          path: |
            README.md
            package.json
            package-lock.json
            dist
          retention-days: 1
          if-no-files-found: error

  create-release:
    permissions:
      contents: write
    needs: build
    uses: cmaster11/gha/.github/workflows/workflow-create-release.yaml@main